keycloak:
  realm: expenses
  resource: expenses-app
spring:
  application:
    name: expenses-service
  datasource:
    url: jdbc:mysql://192.168.123.157:3306/expensesdb?useSSL=false
    username: spring
    password: expenses
    driverClassName: com.mysql.jdbc.Driver
  profiles: prod
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.123.204:8761/eureka/
  appInfo:
    replicate:
      interval: 3
    initial:
      replicate:
        time: 3
  instance:
    statusPageUrlPath: /actuator
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 3
    healthCheckUrlPath: /actuator/health
logging:
  file: myapplication.log
feign:
  client:
    config:
      service:
        booking: expenses-service
        account: account-service
expenses:
  messaging:
    exchange: eventExchange
    bookingProcessedQueueName: bookingServiceQueue
    expensesQueueName: expensesServiceQueue